var searchData=
[
  ['leveling_0',['Wear leveling',['../md_DESIGN.html#autotoc_md11',1,'']]],
  ['lfs_1',['lfs',['../structlfs.html',1,'']]],
  ['lfs_5fattr_2',['lfs_attr',['../structlfs__attr.html',1,'']]],
  ['lfs_5fcache_3',['lfs_cache',['../structlfs__cache.html',1,'']]],
  ['lfs_5fcommit_4',['lfs_commit',['../structlfs__commit.html',1,'']]],
  ['lfs_5fconfig_5',['lfs_config',['../structlfs__config.html',1,'']]],
  ['lfs_5fctz_6',['lfs_ctz',['../structlfs__file_1_1lfs__ctz.html',1,'lfs_file']]],
  ['lfs_5fdir_7',['lfs_dir',['../structlfs__dir.html',1,'']]],
  ['lfs_5fdir_5fcommit_5fcommit_8',['lfs_dir_commit_commit',['../structlfs__dir__commit__commit.html',1,'']]],
  ['lfs_5fdir_5ffind_5fmatch_9',['lfs_dir_find_match',['../structlfs__dir__find__match.html',1,'']]],
  ['lfs_5fdir_5ftraverse_10',['lfs_dir_traverse',['../structlfs__dir__traverse.html',1,'']]],
  ['lfs_5fdiskoff_11',['lfs_diskoff',['../structlfs__diskoff.html',1,'']]],
  ['lfs_5ffcrc_12',['lfs_fcrc',['../structlfs__fcrc.html',1,'']]],
  ['lfs_5ffile_13',['lfs_file',['../structlfs__file.html',1,'']]],
  ['lfs_5ffile_5fconfig_14',['lfs_file_config',['../structlfs__file__config.html',1,'']]],
  ['lfs_5ffs_5fparent_5fmatch_15',['lfs_fs_parent_match',['../structlfs__fs__parent__match.html',1,'']]],
  ['lfs_5ffsinfo_16',['lfs_fsinfo',['../structlfs__fsinfo.html',1,'']]],
  ['lfs_5fgstate_17',['lfs_gstate',['../structlfs__gstate.html',1,'']]],
  ['lfs_5finfo_18',['lfs_info',['../structlfs__info.html',1,'']]],
  ['lfs_5flookahead_19',['lfs_lookahead',['../structlfs_1_1lfs__lookahead.html',1,'lfs']]],
  ['lfs_5fmattr_20',['lfs_mattr',['../structlfs__mattr.html',1,'']]],
  ['lfs_5fmdir_21',['lfs_mdir',['../structlfs__mdir.html',1,'']]],
  ['lfs_5fmlist_22',['lfs_mlist',['../structlfs_1_1lfs__mlist.html',1,'lfs']]],
  ['lfs_5fsuperblock_23',['lfs_superblock',['../structlfs__superblock.html',1,'']]],
  ['lfs_5ftype_5fcrc_24',['&lt;tt&gt;0x5xx&lt;/tt&gt; LFS_TYPE_CRC',['../md_SPEC.html#autotoc_md68',1,'']]],
  ['lfs_5ftype_5fcreate_25',['&lt;tt&gt;0x401&lt;/tt&gt; LFS_TYPE_CREATE',['../md_SPEC.html#autotoc_md36',1,'']]],
  ['lfs_5ftype_5fctzstruct_26',['&lt;tt&gt;0x202&lt;/tt&gt; LFS_TYPE_CTZSTRUCT',['../md_SPEC.html#autotoc_md54',1,'']]],
  ['lfs_5ftype_5fdelete_27',['&lt;tt&gt;0x4ff&lt;/tt&gt; LFS_TYPE_DELETE',['../md_SPEC.html#autotoc_md38',1,'']]],
  ['lfs_5ftype_5fdir_28',['&lt;tt&gt;0x002&lt;/tt&gt; LFS_TYPE_DIR',['../md_SPEC.html#autotoc_md44',1,'']]],
  ['lfs_5ftype_5fdirstruct_29',['&lt;tt&gt;0x200&lt;/tt&gt; LFS_TYPE_DIRSTRUCT',['../md_SPEC.html#autotoc_md50',1,'']]],
  ['lfs_5ftype_5ffcrc_30',['&lt;tt&gt;0x5ff&lt;/tt&gt; LFS_TYPE_FCRC',['../md_SPEC.html#autotoc_md70',1,'']]],
  ['lfs_5ftype_5fgstate_31',['&lt;tt&gt;0x7xx&lt;/tt&gt; LFS_TYPE_GSTATE',['../md_SPEC.html#autotoc_md64',1,'']]],
  ['lfs_5ftype_5fhardtail_32',['&lt;tt&gt;0x601&lt;/tt&gt; LFS_TYPE_HARDTAIL',['../md_SPEC.html#autotoc_md62',1,'']]],
  ['lfs_5ftype_5finlinestruct_33',['&lt;tt&gt;0x201&lt;/tt&gt; LFS_TYPE_INLINESTRUCT',['../md_SPEC.html#autotoc_md52',1,'']]],
  ['lfs_5ftype_5fmovestate_34',['&lt;tt&gt;0x7ff&lt;/tt&gt; LFS_TYPE_MOVESTATE',['../md_SPEC.html#autotoc_md66',1,'']]],
  ['lfs_5ftype_5fname_35',['&lt;tt&gt;0x0xx&lt;/tt&gt; LFS_TYPE_NAME',['../md_SPEC.html#autotoc_md40',1,'']]],
  ['lfs_5ftype_5freg_36',['&lt;tt&gt;0x001&lt;/tt&gt; LFS_TYPE_REG',['../md_SPEC.html#autotoc_md42',1,'']]],
  ['lfs_5ftype_5fsofttail_37',['&lt;tt&gt;0x600&lt;/tt&gt; LFS_TYPE_SOFTTAIL',['../md_SPEC.html#autotoc_md60',1,'']]],
  ['lfs_5ftype_5fstruct_38',['&lt;tt&gt;0x2xx&lt;/tt&gt; LFS_TYPE_STRUCT',['../md_SPEC.html#autotoc_md48',1,'']]],
  ['lfs_5ftype_5fsuperblock_39',['&lt;tt&gt;0x0ff&lt;/tt&gt; LFS_TYPE_SUPERBLOCK',['../md_SPEC.html#autotoc_md46',1,'']]],
  ['lfs_5ftype_5ftail_40',['&lt;tt&gt;0x6xx&lt;/tt&gt; LFS_TYPE_TAIL',['../md_SPEC.html#autotoc_md58',1,'']]],
  ['lfs_5ftype_5fuserattr_41',['&lt;tt&gt;0x3xx&lt;/tt&gt; LFS_TYPE_USERATTR',['../md_SPEC.html#autotoc_md56',1,'']]],
  ['license_42',['LICENSE',['../md_LICENSE.html',1,'']]],
  ['license_43',['License',['../md_README.html#autotoc_md28',1,'']]],
  ['lists_44',['CTZ skip-lists',['../md_DESIGN.html#autotoc_md6',1,'']]],
  ['littlefs_45',['littlefs',['../md_README.html',1,'littlefs'],['../md_DESIGN.html#autotoc_md3',1,'littlefs'],['../md_DESIGN.html',1,'The design of littlefs']]],
  ['littlefs_20technical_20specification_46',['littlefs technical specification',['../md_SPEC.html',1,'']]]
];
